version: "3"

services:
    web:
        build:
            context: ./
            dockerfile: Docker/Dockerfile
        container_name: web
        hostname: web
        volumes:
            - ./app:/app
        ports:
            - "3000:3000"
        depends_on:
            - postgres
        command: go run index.go
    postgres:
        build:
            context: postgres/Docker
            dockerfile: Dockerfile
        container_name: postgres
        hostname: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
