version: "3"

services:
    postgres:
        build:
            context: postgres/Docker
            dockerfile: Dockerfile
        container_name: postgres
        hostname: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
